encyclopedia/urls.py
from django.urls import path
from . import views

app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/random", views.random_entry, name="random"),
    path("wiki/<str:title>", views.pages, name="pages"),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("wiki/<str:title>/edit", views.edit, name="edit")
]
    

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import markdown
import random

from . import util

from . import urls


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def pages(request, title):
    entries = util.list_entries()
    if title in entries:
    #get the entry(in markdown) by its title
        title_page = util.get_entry(title)
        md = markdown.Markdown()
        return render(request, "encyclopedia/pages.html",
        {
        "text": md.convert(title_page),
        "title": title
        })
    else:
        error = "404 Error: The requested URL was not found"
        return render(request,"encyclopedia/error.html",
        {
            "error" : error
        })

    

        

def search(request):
    # get the value of the form
    search_item = request.GET.get("q")
    # check if the value matches the entries in the form
    entries = util.list_entries()
    if search_item in entries:
        return HttpResponseRedirect(f"/wiki/{search_item}")
    else:
        #return a list which have the search value as a substring
        
        substring_list =[]
        for entry in entries:
            if search_item in entry:
                substring_list.append(entry)
        return render(request,"encyclopedia/search.html",
        {
            "substring_list": substring_list
        })
        


def create(request):
    if request.method=="GET":
        return render(request, "encyclopedia/create.html")
    else:
        title = request.POST.get("title")
        description = request.POST.get("description")
        # check if title already exist, render an error message

        entries = util.list_entries()
        if title in entries:
            error = "This page already exists."
            return render(request,"encyclopedia/error.html",
            {
                "error": error
            })
        else:
            # save the entry and redirect user to the new page
            util.save_entry(title, description)
            return HttpResponseRedirect(f"/wiki/{title}")



def edit(request,title):
    # render the page for user to edit the content if user reach route via GET
    if request.method=="GET":
        title_page = util.get_entry(title)
        return render(request, "encyclopedia/edit.html",
        {
        "text": title_page,
        "title": title
        })
    
    # if user reach route via POST(save the edits) 
    else:
        new_description = request.POST.get("new_description")
        # save the user entry and replace the current file
        util.save_entry(title, new_description)
        #redirect user to the new page
        return HttpResponseRedirect(f"/wiki/{title}")




def random_entry(request):
    # get a list of all the entries
    entries = util.list_entries()

    # get a random number bewteen 0 and the length of list
    rand_number = random.randint(0,len(entries)-1)
    page = entries[rand_number]
    return HttpResponseRedirect(f"/wiki/{page}")











    

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create Page
{% endblock %}

{% block body %}
    <h1>Create a new page</h1>

    <hr>

    <form action="{% url 'encyclopedia:create' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title</label>
        </div>
        <div class="form-group w-80">
            <textarea class="form-control rounded-0" rows = "1" cols="2" name = "title" placeholder="Insert the title of your page" required></textarea>
        </div>

        <div class="form-group w-80">
            <label for="content">Content </label>
            <textarea class="form-control rounded-0" rows = "15" cols="2" name = "description" placeholder="Insert your content in markdown format here" required></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit new page</button>
    </form>
        

   

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Edit Page
{% endblock %}

{% block body %}

<h1>Edit Page for {{title}}</h1>
<hr>
<form action="/wiki/{{title}}/edit", method="POST">
    {% csrf_token %}
    <div class="form-group w-80">
        <label for="content">Content </label>
        <textarea class="form-control rounded-0" rows = "10" cols="2" name = "new_description" required>{{text|safe}}</textarea>
    </div>
    <button class="btn btn-primary" type="submit">Save the edits</button>
</form>




  
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1> {{error}}</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="explore">
        <h1 class="main-page">Explore the pages below</h1>
        <hr>
        <ul>
            {% for entry in entries %}
                <li><a href="/wiki/{{entry}}">{{entry}}</a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-3 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}" title="Go back to Main Page">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}" title="Contribute to create a new page">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}" title="Visit a randomly selected page">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-9 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/pages.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
<div class="page">
  {{text|safe}}
  <form action="/wiki/{{title}}/edit", method="GET">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Edit Page</button>
  </form>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Results
{% endblock %}

{% block body %}
    <h1>Search Results</h1>
    <hr>
    <ul>
        {% for entry in substring_list %}
            <li><a href="/wiki/{{entry}}">{{entry}}</a></li>
        {% empty %}
           <h2>The page that you have requested for is not found</h2>
        {% endfor %}
    </ul>
{% endblock %}